<x-layouts.app :title="$record ? 'Ubah pengguna' : 'Tambah pengguna'">
    <div class="mb-6"><a class="text-sm font-semibold text-brand-700" href="{{ route('users.index') }}">← Kembali</a><h1 class="mt-2 text-2xl font-bold text-slate-900">{{ $record ? 'Ubah pengguna' : 'Tambah pengguna' }}</h1><p class="mt-1 text-sm text-slate-500">Role dapat dipilih lebih dari satu. Scope KSM wajib untuk role KSM.</p></div>
    <form method="POST" action="{{ $record ? route('users.update', $record->id) : route('users.store') }}" class="space-y-5">@csrf @if($record)@method('PUT')@endif
        <section class="card"><h2 class="mb-4 font-bold text-slate-900">Identitas akun</h2><div class="grid gap-4 sm:grid-cols-2"><div><label for="name">Nama lengkap</label><input id="name" name="name" value="{{ old('name', $record->name ?? '') }}" required></div><div><label for="email">Email</label><input id="email" name="email" type="email" value="{{ old('email', $record->email ?? '') }}" required></div><div><label for="phone">Nomor HP</label><input id="phone" name="phone" value="{{ old('phone', $record->phone ?? '') }}"></div><div><label for="job_title">Jabatan</label><input id="job_title" name="job_title" value="{{ old('job_title', $record->job_title ?? '') }}"></div></div></section>
        <section class="card"><h2 class="mb-1 font-bold text-slate-900">Kata sandi</h2><p class="mb-4 text-sm text-slate-500">{{ $record ? 'Kosongkan jika tidak ingin mengganti kata sandi.' : 'Gunakan minimal 12 karakter.' }}</p><div class="grid gap-4 sm:grid-cols-2"><div><label for="password">Kata sandi</label><input id="password" name="password" type="password" {{ $record ? '' : 'required' }}></div><div><label for="password_confirmation">Konfirmasi</label><input id="password_confirmation" name="password_confirmation" type="password" {{ $record ? '' : 'required' }}></div></div></section>
        <section class="card"><h2 class="font-bold text-slate-900">Role</h2><div class="mt-4 grid gap-3 sm:grid-cols-2">@foreach($roles as $role)@continue($role->code === 'super-admin' && !in_array('super-admin', auth()->user()->roleCodes(), true))<label class="flex items-start gap-3 rounded-xl border border-slate-200 p-3 font-normal"><input name="role_ids[]" type="checkbox" value="{{ $role->id }}" {{ in_array($role->id, old('role_ids', $selectedRoles)) ? 'checked' : '' }}><span><span class="block font-semibold text-slate-800">{{ $role->name }}</span><span class="text-xs text-slate-500">{{ $role->code }}</span></span></label>@endforeach</div></section>
        <section class="card"><h2 class="font-bold text-slate-900">Scope KSM</h2><p class="mt-1 text-sm text-slate-500">Pilih semua KSM yang boleh diakses pengguna.</p><div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@forelse($departments as $department)<label class="flex items-center gap-3 rounded-xl border border-slate-200 p-3 font-normal"><input name="department_ids[]" type="checkbox" value="{{ $department->id }}" {{ in_array($department->id, old('department_ids', $selectedDepartments)) ? 'checked' : '' }}><span>{{ $department->name }}</span></label>@empty<p class="text-sm text-amber-700">Buat master KSM terlebih dahulu bila role memerlukan scope.</p>@endforelse</div></section>
        @if($record)<section class="card"><label for="change_reason">Alasan perubahan <span class="text-red-600">*</span></label><textarea id="change_reason" name="change_reason" rows="3" required>{{ old('change_reason') }}</textarea></section>@endif
        <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a class="btn-secondary" href="{{ route('users.index') }}">Batal</a><button class="btn-primary" type="submit">Simpan pengguna</button></div>
    </form>
    @if($record && auth()->user()->hasPermission('users.status'))<section class="card mt-8 border-amber-200"><h2 class="font-bold text-slate-900">Status akun</h2><p class="mt-1 text-sm text-slate-500">Menonaktifkan akun akan menghapus session aktif pengguna.</p><form method="POST" action="{{ route('users.status', $record->id) }}" class="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $record->is_active ? 0 : 1 }}"><div><label for="status_reason">Alasan</label><input id="status_reason" name="change_reason" required minlength="5"></div><button class="btn-secondary self-end" type="submit">{{ $record->is_active ? 'Nonaktifkan' : 'Aktifkan' }} akun</button></form></section>@endif
</x-layouts.app>
