<x-layouts.app title="Pratinjau impor">
    @include('admissions.nav')<h1 class="mb-2 text-2xl font-bold">Pratinjau & hasil impor</h1><p class="mb-5 text-sm">{{ $rows->where('status','committed')->count() }} dari {{ $rows->count() }} baris berhasil. Perbaiki sumber untuk data tidak valid, lalu unggah ulang. Kandidat dinilai ulang saat konfirmasi.</p>
    <p class="mb-4 text-sm">Status sumber privat: {{ $source?->scan_status ?? 'belum tersedia' }}. Sumber tertahan perlu diunggah ulang setelah pemeriksa berkas siap.</p><form method="POST" action="{{ route('admissions.import-commit', $import->ulid) }}">@csrf<div class="space-y-3">@foreach($rows as $row)@php($payload = json_decode($row->payload, true))@php($issues = json_decode($row->issues, true))<div class="card"><p class="font-semibold">Baris {{ $row->row_number }} · {{ $payload['name'] ?: '(nama tidak valid)' }} · {{ $row->status }}</p><p class="text-xs text-slate-500">NIM {{ $payload['nim'] ?? '—' }}</p>@if($row->status !== 'committed')
        @if(isset($payload['_error']))<p class="mt-2 text-sm text-red-700">{{ $payload['_error'] }}</p>@endif
        @foreach($issues as $issue)<p class="mt-2 text-sm text-amber-800">{{ is_array($issue) ? (isset($issue['reasons']) ? ($issue['number'].' · '.$issue['name'].' · '.implode('; ', $issue['reasons'])) : implode('; ', $issue)) : $issue }}</p>@endforeach
        <div class="mt-3 grid gap-3 md:grid-cols-2"><label>ULID peserta lama (opsional)<input name="choices[{{ $row->row_number }}][existing_ulid]" placeholder="Pilih eksplisit setelah pemeriksaan">@foreach($issues as $issue)@if(is_array($issue) && isset($issue['ulid']))<span class="block select-all text-xs font-normal">{{ $issue['ulid'] }}</span>@endif @endforeach</label><label>Alasan pemilihan / kandidat berbeda<textarea name="choices[{{ $row->row_number }}][reason]" maxlength="2000"></textarea></label></div>@endif</div>@endforeach</div>
        <div class="card mt-5 space-y-3"><label class="flex gap-2"><input name="confirmed" type="checkbox" value="1" required> Saya telah memeriksa setiap baris dan keputusan identitas</label><button class="btn-primary">Konfirmasi / ulangi baris yang gagal</button></div>
    </form>
</x-layouts.app>
