<x-layouts.app title="Data induk peserta">
    @include('admissions.nav')
    <h1 class="mb-2 text-2xl font-bold">Data induk peserta</h1><p class="mb-5 text-sm text-slate-500">Cari peserta lama terlebih dahulu. Peserta yang kembali menggunakan nomor yang sama dengan penempatan baru.</p>
    <form class="mb-5 flex items-end gap-3"><label class="flex-1">Nama, nomor peserta, atau NIM<input name="q" value="{{ request('q') }}"></label><button class="btn-primary">Cari</button></form>
    <div class="card mb-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr><th class="p-2">Nomor / nama</th><th class="p-2">NIM</th><th class="p-2">Tindakan</th></tr></thead><tbody>@forelse($participants as $p)<tr class="border-t"><td class="p-2">{{ $p->number }}<p class="font-semibold">{{ $p->name }}</p></td><td class="p-2">{{ $p->nim ?? '—' }}</td><td class="p-2"><a class="text-brand-700 underline" href="{{ route('admissions.create', ['participant' => $p->ulid]) }}">Tambah penempatan</a><a class="ml-3 text-brand-700 underline" href="{{ route('admissions.participant-edit', $p->ulid) }}">Ubah data / foto</a><details class="mt-2"><summary class="cursor-pointer">Aktivasi akun</summary><form class="mt-3 space-y-2" method="POST" action="{{ route('admissions.activate', $p->ulid) }}">@csrf<label class="block">Email akun<input name="email" type="email" required></label><label class="block">Bukti pemeriksaan kepemilikan<textarea name="ownership_reason" minlength="10" required></textarea></label><label class="flex gap-2"><input type="checkbox" name="ownership_confirmed" value="1" required> Kepemilikan sudah diperiksa</label><button class="btn-secondary">Aktifkan setelah verifikasi</button></form></details></td></tr>@empty<tr><td colspan="3" class="p-6 text-center">Belum ada peserta yang cocok.</td></tr>@endforelse</tbody></table>{{ $participants->links() }}</div>
    <details class="card" @if($errors->any()) open @endif><summary class="cursor-pointer text-lg font-bold">Daftarkan peserta baru</summary><form class="mt-4 grid gap-4 md:grid-cols-2" method="POST" action="{{ route('admissions.participant-preview') }}">@csrf
        <label>Nama sesuai identitas<input name="name" value="{{ old('name') }}" maxlength="255" required></label><label>Tanggal lahir<input type="date" name="birth_date" value="{{ old('birth_date') }}"></label>
        <label>NIK (opsional, 16 digit)<input name="nik" inputmode="numeric" pattern="[0-9]{16}" maxlength="16" value="{{ old('nik') }}"></label><label>NIM (simpan nol di depan)<input name="nim" value="{{ old('nim') }}" maxlength="100"></label>
        <label>Email kontak<input name="email" type="email" value="{{ old('email') }}"></label><label>Institusi<select name="institution_id" required><option value="">Pilih institusi</option>@foreach($institutions as $i)<option value="{{ $i->id }}" @selected(old('institution_id') == $i->id)>{{ $i->name }}</option>@endforeach</select></label><div><button class="btn-primary">Periksa kandidat duplikat</button></div>
    </form></details>
</x-layouts.app>
