<x-layouts.app title="Detail penempatan">
    @include('admissions.nav')
    @php $snapshot = json_decode($p->snapshot, true); @endphp
    <div class="card mb-5"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-sm text-slate-500">{{ $participant->number }} · Revisi {{ $p->revision }}</p><h1 class="mt-1 text-2xl font-bold">{{ $participant->name }}</h1></div><span class="badge-muted">{{ $p->status }}</span></div><p class="mt-3">{{ $snapshot['department'] }} · {{ $snapshot['program'] }} · {{ $snapshot['participant_type'] }}</p><p class="text-sm text-slate-500">{{ $snapshot['institution'] }} · {{ $p->start_date }} sampai {{ $p->end_date }} (inklusif)</p><p class="mt-3 text-xs">KSM: {{ $p->ksm_status }} · Kordik: {{ $p->kordik_status }} · Dokumen: {{ $p->document_status }}</p></div>
    @if($conflicts->isNotEmpty())<div class="card mb-5 border-amber-300"><h2 class="font-bold">Peringatan periode bertumpang tindih</h2>@foreach($conflicts as $c)<p class="mt-2 text-sm"><a class="text-brand-700 underline" href="{{ route('admissions.show', $c->ulid) }}">{{ $c->ulid }}</a> · {{ json_decode($c->snapshot, true)['department'] }} · {{ $c->start_date }} — {{ $c->actual_end_date ?? $c->end_date }}</p>@endforeach<p class="mt-3 text-sm">Draft belum memesan periode. Konflik dalam KSM yang sama harus diselesaikan dengan perubahan penempatan lama.</p></div>@endif
    @php
        $actions = [];
        if($access->admin(auth()->user())) {
            if($p->status === 'draft') $actions['submit'] = 'Ajukan ke KSM';
            if($p->status === 'menunggu_dokumen' && $access->role(auth()->user(), ['admin-kordik'])) $actions['verify'] = 'Verifikasi checklist lengkap';
            if(in_array($p->status, ['ditolak_ksm','ditolak_kordik','dibatalkan'])) $actions['revise'] = 'Revisi kembali ke draft';
            if(in_array($p->status, ['draft','menunggu_konfirmasi_ksm','menunggu_persetujuan_kordik','menunggu_dokumen','terverifikasi','dijadwalkan'])) $actions['cancel'] = 'Batalkan penempatan';
        }
        if($access->role(auth()->user(), ['ketua-ksm']) && in_array((int)$p->department_id, auth()->user()->departmentScopeIds()) && $p->status === 'menunggu_konfirmasi_ksm') $actions += ['ksm_accept' => 'KSM tersedia / terima', 'ksm_reject' => 'KSM menolak'];
        if($access->role(auth()->user(), ['tim-kordik'])) {
            if($p->status === 'menunggu_persetujuan_kordik') $actions += ['kordik_accept' => 'Setujui penerimaan', 'kordik_reject' => 'Tolak penerimaan'];
            if(in_array($p->status, ['sedang_stase','menunggu_penyelesaian'])) $actions['cancel'] = 'Setujui pembatalan setelah mulai';
            if($p->status === 'selesai') $actions['reopen'] = 'Buka kembali penyelesaian';
        }
    @endphp
    @if($actions)<form class="card mb-5 space-y-3" method="POST" action="{{ route('admissions.transition', $p->ulid) }}">@csrf<input type="hidden" name="expected_status" value="{{ $p->status }}"><input type="hidden" name="revision" value="{{ $p->revision }}"><h2 class="font-bold">Tindak lanjut</h2><label class="block">Keputusan<select name="action">@foreach($actions as $key => $label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></label><label class="block">Alasan (wajib untuk tolak, batal, revisi, buka kembali)<textarea name="reason" maxlength="2000">{{ old('reason') }}</textarea></label><button class="btn-primary">Simpan keputusan</button></form>@endif
    <div class="grid items-start gap-5 xl:grid-cols-2"><section class="card"><h2 class="mb-4 text-lg font-bold">Checklist dokumen</h2>@foreach($documents as $doc)<div class="border-t py-3"><div class="flex justify-between gap-2"><p>{{ $doc->label }}</p><span class="badge-muted">{{ $doc->status }}</span></div>@if($doc->valid_until)<p class="text-xs text-slate-500">Berlaku sampai {{ $doc->valid_until }}</p>@endif
        @if($p->status === 'menunggu_dokumen' && $access->role(auth()->user(), ['admin-kordik','tim-kordik']))<details class="mt-2"><summary class="cursor-pointer text-sm text-brand-700">Review / pengecualian</summary><form class="mt-3 space-y-3" method="POST" action="{{ route('admissions.review', $p->ulid) }}">@csrf<input type="hidden" name="code" value="{{ $doc->code }}"><label class="block">Keputusan<select name="status">@if($access->role(auth()->user(), ['admin-kordik']))<option value="valid">Valid</option><option value="rejected">Tolak dokumen</option>@endif @if($access->role(auth()->user(), ['tim-kordik']))<option value="exception">Setujui pengecualian persyaratan</option>@endif</select></label><label class="block">Versi berkas<select name="file_ulid"><option value="">Pilih untuk review valid</option>@foreach($files->where('scan_status','clean') as $f)<option value="{{ $f->ulid }}">{{ $f->category }} · v{{ $f->version }} · {{ $f->original_name }}</option>@endforeach</select></label><label class="block">Berlaku sampai (bila ada)<input type="date" name="valid_until"></label><label class="block">Alasan / hasil pemeriksaan<textarea name="reason" required minlength="10" maxlength="2000"></textarea></label><button class="btn-secondary">Simpan review</button></form></details>@endif
    </div>@endforeach</section>
    <section class="card"><h2 class="mb-4 text-lg font-bold">Berkas privat</h2>@forelse($files as $file)<div class="border-t py-3 text-sm"><p class="font-semibold">{{ $file->category }} · Versi {{ $file->version }}</p><p>{{ $file->original_name }} · {{ $file->scan_status }}</p>@if($file->scan_status === 'clean')<a class="text-brand-700 underline" href="{{ route('admissions.download', $file->ulid) }}">Unduh berkas</a>@endif</div>@empty<p class="text-sm text-slate-500">Belum ada berkas yang dapat Anda akses.</p>@endforelse
    @if($access->role(auth()->user(), ['admin-kordik']))<details class="mt-5"><summary class="cursor-pointer font-semibold">Unggah dokumen penempatan</summary><div class="mt-3">@include('admissions.upload', ['resource' => 'placement', 'resourceUlid' => $p->ulid, 'categories' => ['ijazah','bhd','sip','str','kompetensi','pendukung','administrasi']])</div></details>@endif</section></div>
    @if($access->admin(auth()->user()) && in_array($p->status, ['draft','menunggu_konfirmasi_ksm','menunggu_persetujuan_kordik','menunggu_dokumen','terverifikasi']))<details class="card mt-5"><summary class="cursor-pointer font-bold">Revisi periode / KSM</summary><p class="my-3 text-sm">Revisi mengembalikan ke draft dan mengulang persetujuan. Persetujuan pengecualian lama tidak berlaku untuk periode baru.</p><form class="grid gap-3 md:grid-cols-2" method="POST" action="{{ route('admissions.period', $p->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $p->revision }}"><label>Mulai<input type="date" name="start_date" value="{{ $p->start_date }}" required></label><label>Selesai<input type="date" name="end_date" value="{{ $p->end_date }}" required></label><label>KSM<select name="department_id">@foreach($departments as $d)<option value="{{ $d->id }}" @selected($p->department_id == $d->id)>{{ $d->name }}</option>@endforeach</select></label><label>Alasan<textarea name="reason" required minlength="10" maxlength="2000"></textarea></label><div><button class="btn-secondary">Simpan revisi</button></div></form></details>@endif
    @if($access->admin(auth()->user()) && $p->status === 'draft' && $conflicts->isNotEmpty())<details class="card mt-5"><summary class="cursor-pointer font-bold">Minta pengecualian paralel lintas KSM</summary><form class="mt-4 space-y-3" method="POST" action="{{ route('admissions.exception', $p->ulid) }}">@csrf<label class="block">Penempatan yang bentrok<select name="conflict_ulid">@foreach($conflicts->where('department_id','!=',$p->department_id) as $c)<option value="{{ $c->ulid }}">{{ $c->ulid }} · {{ $c->start_date }} — {{ $c->end_date }}</option>@endforeach</select></label><label class="block">Dokumen pendukung bersih<select name="file_ulid" required><option value="">Pilih berkas</option>@foreach($files->where('category','pendukung')->where('scan_status','clean') as $f)<option value="{{ $f->ulid }}">{{ $f->original_name }} · v{{ $f->version }}</option>@endforeach</select></label><label class="block">Alasan program paralel<textarea name="reason" minlength="10" maxlength="2000" required></textarea></label><button class="btn-secondary">Kirim permohonan</button></form></details>@endif
    @if($exceptions->isNotEmpty())<section class="card mt-5"><h2 class="font-bold">Keputusan pengecualian overlap</h2>@foreach($exceptions as $e)<div class="mt-3 border-t pt-3"><p class="text-sm">{{ $e->reason }} · <strong>{{ $e->status }}</strong></p>@if($e->status === 'pending' && $access->role(auth()->user(), ['tim-kordik']))<form class="mt-3 space-y-3" method="POST" action="{{ route('admissions.exception-decide', $e->ulid) }}">@csrf<label class="block">Keputusan<select name="approved"><option value="1">Setujui</option><option value="0">Tolak</option></select></label><label class="block">Alasan<textarea name="reason" minlength="10" maxlength="2000" required></textarea></label><button class="btn-secondary">Simpan keputusan pengecualian</button></form>@endif</div>@endforeach</section>@endif
    @if($staff)<section class="card mt-5"><h2 class="mb-3 font-bold">Histori penempatan</h2>@foreach($histories as $h)<div class="border-t py-3 text-sm"><p class="font-semibold">{{ $h->action }} · {{ $h->to_status }}</p><p class="text-xs text-slate-500">{{ $h->created_at }} · Petugas #{{ $h->actor_id }}</p>@if($h->reason)<p class="mt-1">{{ $h->reason }}</p>@endif</div>@endforeach</section>@endif
</x-layouts.app>
