<x-layouts.app title="Laporan">
<h1 class="text-2xl font-bold">Laporan</h1><p class="mt-2 text-sm text-slate-600">Data mengikuti peran, KSM, penugasan, dan kepemilikan Anda. Periode penempatan menggunakan irisan tanggal; presensi dan kegiatan juga disaring berdasarkan tanggal kegiatan.</p>
<form class="card my-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" method="get">
<label>Jenis laporan<select class="input" name="type">@foreach(\App\Services\ReportService::TYPES as $key => $label)<option value="{{ $key }}" @selected($type === $key)>{{ $label }}</option>@endforeach</select></label>
@foreach(['institution'=>['Institusi','institution_id','institution_name'], 'department'=>['KSM','department_id','department_name'], 'participant'=>['Peserta','participant_id','name']] as $key=>[$label,$id,$name])<label>{{ $label }}<select name="{{ $key }}"><option value="">Semua dalam cakupan</option>@foreach($choices->unique($id) as $choice)<option value="{{ $choice->$id }}" @selected(($f[$key] ?? '') == $choice->$id)>{{ $choice->$name }}</option>@endforeach</select></label>@endforeach
<label>Penempatan (wajib untuk nilai/logbook)<select name="placement"><option value="">Semua dalam cakupan</option>@foreach($choices as $choice)<option value="{{ $choice->ulid }}" @selected(($f['placement'] ?? '') === $choice->ulid)>{{ $choice->name }} · {{ $choice->department_name }} · {{ $choice->start_date }}</option>@endforeach</select></label>
<label>Status penempatan<select name="status"><option value="">Semua status</option>@foreach(['draft', ...\App\Services\PlacementService::RESERVING, 'ditolak_ksm', 'ditolak_kordik', 'dibatalkan'] as $key)<option value="{{ $key }}" @selected(($f['status'] ?? '') === $key)>{{ ucfirst(str_replace('_', ' ', $key)) }}</option>@endforeach</select></label>
@foreach(['from'=>'Dari tanggal', 'to'=>'Sampai tanggal'] as $key=>$label)<label>{{ $label }}<input name="{{ $key }}" type="date" value="{{ $f[$key] ?? '' }}"></label>@endforeach
<div class="flex flex-wrap gap-2 sm:col-span-2 xl:col-span-4"><button class="btn-primary" name="format" value="html">Tampilkan</button><button class="btn-secondary" name="format" value="xlsx">Excel</button><button class="btn-secondary" name="format" value="pdf">PDF</button></div></form>
<h2 class="mb-3 text-lg font-bold">{{ $title }} · {{ $page->total() }} baris</h2><div class="card overflow-x-auto"><table class="w-full text-sm">@if($rows)<thead><tr>@foreach(array_keys($rows[0]) as $key)<th class="p-2 text-left">{{ $key }}</th>@endforeach</tr></thead><tbody>@foreach($rows as $row)<tr class="border-t">@foreach($row as $key=>$value)<td class="p-2">@if($type === 'placements' && $key === 'Referensi')<a class="underline" href="{{ route('reports', ['placement'=>$value]) }}">{{ $value }}</a>@else{{ $value ?? '—' }}@endif</td>@endforeach</tr>@endforeach</tbody>@else<tr><td>Tidak ada data dalam cakupan/filter ini.</td></tr>@endif</table></div><div class="mt-4">{{ $page->links() }}</div>
</x-layouts.app>
