<x-layouts.app title="Kegiatan penempatan">
    @php($u = auth()->user())
    @php($manage = $a->manage($u, $p->department_id))
    @php($edit = $manage || $a->owner($u, $p))
    @php($open = in_array($p->status, \App\Services\ScheduleService::OPEN_PLACEMENTS))
    <a class="text-sm text-brand-700" href="{{ route('scheduling.index') }}">← Penugasan & jadwal</a>
    <div class="my-5 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-bold">{{ $participant->name }}</h1><p class="text-sm text-slate-600">{{ $participant->number }} · {{ json_decode($p->snapshot)->department }}</p><p class="mt-1 text-sm">{{ \Carbon\Carbon::parse($p->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($p->end_date)->format('d-m-Y') }} · {{ str_replace('_', ' ', $p->status) }}</p></div>@if($edit && $open)<a class="btn-primary" href="{{ route('scheduling.create', $p->ulid) }}">Tambah jadwal</a>@endif</div>
    @if($p->status === 'dijadwalkan' && $a->admin($u))<form class="mb-5" method="POST" action="{{ route('scheduling.start', $p->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $p->revision }}"><button class="btn-secondary">Mulai stase setelah syarat diperiksa</button></form>@endif

    <h2 class="mb-3 text-lg font-semibold">Jadwal kegiatan</h2>
    <div class="grid gap-4 xl:grid-cols-2">@forelse($schedules as $s)<article class="card p-5">
        <div class="flex flex-wrap justify-between gap-2"><h3 class="font-semibold">{{ $s->activity }}</h3><span class="badge-muted">{{ \App\Services\ScheduleService::label($s->status) }} · v{{ $s->revision }}</span></div>
        <p class="mt-2 text-sm">{{ \Carbon\Carbon::parse($s->date)->format('d-m-Y') }} · {{ $s->start_time ? substr($s->start_time, 0, 5).'–'.substr($s->end_time, 0, 5).' WITA' : 'Sepanjang hari' }}</p>
        <p class="text-sm text-slate-500">{{ $s->location_name }} · {{ $s->group_name ?? 'Individual' }}@if($s->examiner_assignment_id) · Penguji: {{ $assignments->firstWhere('id', $s->examiner_assignment_id)?->educator_name }}@endif</p>
        <p class="text-sm text-slate-500">Pembimbing: {{ $assignments->firstWhere('id', $s->mentor_assignment_id)?->educator_name }} @if($s->replaces_id) · {{ $s->change_kind === 'cancel' ? 'Permohonan pembatalan' : 'Versi pengganti' }} #{{ $s->replaces_id }}@endif</p>
        @if($s->notes)<p class="mt-2 whitespace-pre-wrap break-words text-sm">{{ $s->notes }}</p>@endif
        @if($s->reason)<p class="mt-2 break-words text-sm text-slate-500">Alasan: {{ $s->reason }}</p>@endif
        @if($open)
            @if($edit && in_array($s->status, ['draft', 'revision', 'published']))<a class="mt-3 inline-block text-sm font-semibold text-brand-700" href="{{ route('scheduling.edit', [$p->ulid, $s->ulid]) }}">{{ $s->status === 'published' ? 'Ajukan perubahan / pembatalan' : 'Ubah draft' }}</a>@endif
            @php($actions = [])
            @if($edit && $s->status === 'draft') @php($actions['submit'] = 'Ajukan ke pembimbing') @endif
            @if($a->mentor($u, $s) && $s->status === 'submitted') @php($actions += ['approve' => 'Setujui', 'revise' => 'Minta revisi']) @endif
            @if($edit && $s->status === 'approved') @php($actions['publish'] = 'Terbitkan jadwal yang disetujui') @endif
            @if($edit && in_array($s->status, ['draft', 'revision', 'submitted', 'approved'])) @php($actions['withdraw'] = 'Tarik pengajuan') @endif
            @if($a->mentor($u, $s) && $s->status === 'published') @php($actions['complete'] = 'Tandai kegiatan selesai') @endif
            @if(count($actions))<form class="mt-4 space-y-3" method="POST" action="{{ route('scheduling.transition', $s->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $s->revision }}"><label class="block text-sm">Tindakan<select class="input" name="action">@foreach($actions as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="block text-sm">Alasan keputusan / penarikan<textarea class="input" name="reason" minlength="10" maxlength="2000"></textarea></label><button class="btn-secondary">Konfirmasi tindakan</button></form>@endif
        @endif
    </article>@empty<div class="card p-5 text-slate-500">Belum ada jadwal. Pastikan penugasan pembimbing telah disetujui KSM.</div>@endforelse</div>
    <div class="mt-4">{{ $schedules->links() }}</div>

    <details class="card mt-6 p-5" open><summary class="cursor-pointer text-lg font-semibold">Penugasan pendidik</summary><div class="mt-4 space-y-3">
        @forelse($assignments as $assignment)<div class="rounded-xl border border-slate-200 p-4"><p class="font-semibold">{{ $assignment->educator_name }} · {{ ['mentor'=>'Pembimbing','examiner'=>'Penguji','supervisor'=>'Supervisor'][$assignment->role] }}</p><p class="text-sm">{{ \Carbon\Carbon::parse($assignment->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($assignment->end_date)->format('d-m-Y') }} · {{ ['pending'=>'Menunggu KSM','approved'=>'Disetujui','rejected'=>'Ditolak','replaced'=>'Digantikan'][$assignment->status] }}</p><p class="mt-1 text-sm text-slate-500">{{ $assignment->reason }}</p>
        @if($assignment->status === 'pending' && $a->chief($u, $p->department_id))<form class="mt-3 flex flex-wrap items-end gap-3" method="POST" action="{{ route('scheduling.assignment-decide', $assignment->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $assignment->revision }}"><label>Keputusan<select class="input" name="action"><option value="approve">Setujui</option><option value="reject">Tolak</option></select></label><label class="min-w-0 flex-1">Alasan<input class="input" name="reason" required minlength="10" maxlength="2000"></label><button class="btn-secondary">Konfirmasi</button></form>@endif</div>@empty<p class="text-sm text-slate-500">Belum ada penugasan.</p>@endforelse
        @if($manage && $open)<form class="grid gap-4 border-t border-slate-200 pt-4 md:grid-cols-2" method="POST" action="{{ route('scheduling.assignment', $p->ulid) }}">@csrf
            <label>Pendidik<select class="input" name="educator_id" required><option value="">Pilih pendidik</option>@foreach($educators as $e)<option value="{{ $e->id }}">{{ $e->name }}</option>@endforeach</select></label>
            <label>Peran penugasan<select class="input" name="role"><option value="mentor">Pembimbing</option><option value="examiner">Penguji</option><option value="supervisor">Supervisor</option></select></label>
            <label>Mulai<input class="input" type="date" name="start_date" value="{{ $p->start_date }}" required></label><label>Selesai<input class="input" type="date" name="end_date" value="{{ $p->end_date }}" required></label>
            <label>Kelompok (opsional)<select class="input" name="clinical_group_id"><option value="">Individual</option>@foreach($groups as $g)<option value="{{ $g->id }}">{{ $g->name }}</option>@endforeach</select></label>
            <label>Menggantikan penugasan (opsional)<select class="input" name="replaces_id"><option value="">Penugasan tambahan</option>@foreach($assignments->where('status', 'approved') as $old)<option value="{{ $old->id }}">{{ $old->educator_name }} · {{ $old->role }}</option>@endforeach</select></label>
            <label class="md:col-span-2">Alasan penugasan / pergantian<textarea class="input" name="reason" required minlength="10" maxlength="2000"></textarea></label><button class="btn-primary">Ajukan penugasan ke KSM</button>
        </form>@endif
    </div></details>

    <details class="card mt-6 p-5"><summary class="cursor-pointer text-lg font-semibold">Kelompok dan histori keanggotaan</summary><div class="mt-4 space-y-3">
    @forelse($memberships as $m)<div class="rounded-xl border border-slate-200 p-4"><p>{{ $m->name }} · {{ \Carbon\Carbon::parse($m->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($m->end_date)->format('d-m-Y') }}</p>
    @if($manage && $open)<form class="mt-3 flex flex-wrap items-end gap-3" method="POST" action="{{ route('scheduling.membership-end', $m->id) }}">@csrf<input type="hidden" name="expected_end_date" value="{{ $m->end_date }}"><label>Akhir keanggotaan<input class="input" type="date" name="end_date" required></label><label class="min-w-0 flex-1">Alasan pindah<input class="input" name="reason" required minlength="10" maxlength="2000"></label><button class="btn-secondary">Akhiri keanggotaan</button></form>@endif</div>@empty<p class="text-sm text-slate-500">Penempatan individual.</p>@endforelse
    @if($manage && $open)<form class="grid gap-4 md:grid-cols-2" method="POST" action="{{ route('scheduling.join', $p->ulid) }}">@csrf<label>Kelompok<select class="input" name="clinical_group_id" required>@foreach($groups as $g)<option value="{{ $g->id }}">{{ $g->name }}</option>@endforeach</select></label><label>Mulai<input class="input" type="date" name="start_date" value="{{ $p->start_date }}" required></label><label>Selesai<input class="input" type="date" name="end_date" value="{{ $p->end_date }}" required></label><label>Alasan<input class="input" name="reason" required minlength="10" maxlength="2000"></label><button class="btn-secondary">Tambahkan keanggotaan</button></form>@endif
    </div></details>

    <details class="card mt-6 p-5"><summary class="cursor-pointer text-lg font-semibold">Perpanjangan stase</summary><div class="mt-4 space-y-3">
    @forelse($extensions as $e)<div class="rounded-xl border border-slate-200 p-4"><p>Akhir baru: {{ \Carbon\Carbon::parse($e->new_end_date)->format('d-m-Y') }} · {{ ['pending_ksm'=>'Menunggu KSM','pending_kordik'=>'Menunggu Tim Kordik','approved'=>'Disetujui','rejected'=>'Ditolak','withdrawn'=>'Ditarik'][$e->status] }}</p><p class="text-sm text-slate-500">{{ $e->reason }}</p>@foreach(json_decode($e->conflict_snapshot) as $conflict)<p class="mt-2 text-sm">Benturan: {{ $conflict->department }} · {{ \Carbon\Carbon::parse($conflict->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($conflict->end_date)->format('d-m-Y') }}</p>@endforeach @if($e->supporting_file_ulid && ($manage || $a->chief($u, $p->department_id) || $a->role($u, ['tim-kordik'])))<a class="text-sm text-brand-700" href="{{ route('admissions.download', $e->supporting_file_ulid) }}">Unduh bukti pendukung</a>@endif
    @if(in_array($e->status, ['pending_ksm', 'pending_kordik']) && ($a->admin($u) || ($e->status === 'pending_ksm' ? $a->chief($u, $p->department_id) : $a->role($u, ['tim-kordik']))))<form class="mt-3 flex flex-wrap items-end gap-3" method="POST" action="{{ route('scheduling.extension-decide', $e->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $e->revision }}">@if(count(json_decode($e->conflict_snapshot, true)))<label class="w-full"><input type="checkbox" name="approve_overlap" value="1"> Saya menyetujui periode paralel lintas KSM berdasarkan bukti pendukung; benturan jam tetap dilarang.</label>@endif<label>Keputusan<select class="input" name="action">@if($e->status === 'pending_ksm' ? $a->chief($u, $p->department_id) : $a->role($u, ['tim-kordik']))<option value="approve">Setujui</option><option value="reject">Tolak</option>@endif @if($a->admin($u))<option value="withdraw">Tarik permohonan</option>@endif</select></label><label class="min-w-0 flex-1">Alasan<input class="input" name="reason" required minlength="10" maxlength="2000"></label><button class="btn-secondary">Konfirmasi</button></form>@endif</div>@empty<p class="text-sm text-slate-500">Belum ada permohonan perpanjangan.</p>@endforelse
    @if($a->admin($u) && $open)<form class="grid gap-4 md:grid-cols-2" method="POST" action="{{ route('scheduling.extension', $p->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $p->revision }}"><label>Bukti periode paralel (jika ada)<select class="input" name="supporting_file_id"><option value="">Tidak ada</option>@foreach($supportingFiles as $file)<option value="{{ $file->id }}">{{ $file->original_name }}</option>@endforeach</select></label><label>Tanggal akhir baru<input class="input" type="date" name="new_end_date" required></label><label>Alasan<input class="input" name="reason" required minlength="10" maxlength="2000"></label><button class="btn-secondary">Ajukan perpanjangan</button></form><p class="text-sm text-slate-500">Perbarui dokumen persyaratan melalui <a class="text-brand-700 underline" href="{{ route('admissions.show', $p->ulid) }}">halaman penerimaan</a> sebelum persetujuan. Penugasan pendidik tidak diperpanjang otomatis.</p>@endif
    </div></details>

    @include('scheduling.history')
</x-layouts.app>
