<x-layouts.app title="Simpan versi logbook">
    <a class="text-sm text-brand-700" href="{{ route('logbooks.placement', $p->ulid) }}">← Logbook penempatan</a>
    <h1 class="mt-3 text-2xl font-bold">{{ $r ? 'Tambahkan versi logbook' : ($kind === 'participant' ? 'Unggah logbook peserta' : 'Catat kegiatan pembimbing') }}</h1>
    <p class="mb-6 mt-2 text-sm text-slate-600">Simpan sebagai draft, lalu ajukan setelah diperiksa. Versi lama tetap tersimpan. Jangan masukkan nama pasien, NIK, nomor rekam medis, diagnosis, atau informasi medis sensitif.</p>
    <form class="card max-w-3xl space-y-5 p-5" method="POST" enctype="multipart/form-data" action="{{ $r ? route('logbooks.update', [$p->ulid, $r->ulid]) : route('logbooks.store', $p->ulid) }}">
        @csrf
        <input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="revision" value="{{ $r->revision ?? 0 }}">
        <div><label class="label" for="type">{{ $kind === 'participant' ? 'Jenis logbook institusi' : 'Jenis kegiatan' }}</label><input class="input" id="type" name="type" maxlength="100" required value="{{ old('type', $r->type ?? '') }}"></div>
        @if($kind === 'educator')
            <div><label class="label" for="author_assignment_id">Penugasan Anda sebagai pembimbing</label><select class="input" id="author_assignment_id" name="author_assignment_id" required><option value="">Pilih penugasan</option>@foreach($assignments->where('role', 'mentor')->where('educator_user_id', auth()->id()) as $a)<option value="{{ $a->id }}" @selected(old('author_assignment_id', $r->author_assignment_id ?? '') == $a->id)>{{ $a->name }} · {{ \Carbon\Carbon::parse($a->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($a->end_date)->format('d-m-Y') }}</option>@endforeach</select></div>
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="date">Tanggal kegiatan</label><input class="input" id="date" type="date" name="date" required value="{{ old('date', $s['date'] ?? '') }}"></div><div><label class="label" for="clinical_location_id">Lokasi</label><select class="input" id="clinical_location_id" name="clinical_location_id" required><option value="">Pilih lokasi</option>@foreach($locations as $l)<option value="{{ $l->id }}" @selected(old('clinical_location_id', $s['clinical_location_id'] ?? '') == $l->id)>{{ $l->name }}</option>@endforeach</select></div></div>
            <div class="grid gap-4 sm:grid-cols-2"><div><label class="label" for="start_time">Jam mulai</label><input class="input" id="start_time" type="time" name="start_time" required value="{{ old('start_time', $s['start_time'] ?? '') }}"></div><div><label class="label" for="end_time">Jam selesai (hari yang sama)</label><input class="input" id="end_time" type="time" name="end_time" required value="{{ old('end_time', $s['end_time'] ?? '') }}"></div></div>
            <div><label class="label" for="material">Materi pembelajaran</label><textarea class="input" id="material" name="material" rows="4" maxlength="4000" required>{{ old('material', $s['material'] ?? '') }}</textarea></div>
        @endif
        <div><label class="label" for="reviewer_assignment_id">{{ $kind === 'participant' ? 'Pembimbing verifikator' : 'Supervisor pemeriksa' }}</label><select class="input" id="reviewer_assignment_id" name="reviewer_assignment_id" required><option value="">Pilih penugasan resmi</option>@foreach($assignments->where('role', $kind === 'participant' ? 'mentor' : 'supervisor')->where('educator_user_id', '!=', auth()->id()) as $a)<option value="{{ $a->id }}" @selected(old('reviewer_assignment_id', $r->reviewer_assignment_id ?? '') == $a->id)>{{ $a->name }} · {{ \Carbon\Carbon::parse($a->start_date)->format('d-m-Y') }} – {{ \Carbon\Carbon::parse($a->end_date)->format('d-m-Y') }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Jika penugasan belum tersedia, minta Admin Kordik mengajukan penugasan untuk disetujui Ketua KSM.</p></div>
        <div><label class="label" for="file">{{ $kind === 'participant' ? 'PDF logbook (wajib)' : 'Lampiran PDF (opsional)' }}</label><input class="input" id="file" type="file" name="file" accept="application/pdf,.pdf" @required($kind === 'participant')><p class="mt-1 text-xs text-slate-500">Maksimal 10 MB. Setiap versi memakai berkas baru; lampiran versi sebelumnya tetap ada dalam riwayat. Pengajuan menunggu pemeriksaan keamanan berkas.</p></div>
        <div><label class="label" for="notes">Catatan</label><textarea class="input" id="notes" name="notes" rows="3" maxlength="2000">{{ old('notes', $s['notes'] ?? '') }}</textarea></div>
        <label class="flex items-start gap-3 text-sm"><input class="mt-1" type="checkbox" name="deidentified" value="1" required @checked(old('deidentified'))><span>Saya telah memeriksa bahwa catatan dan berkas tidak memuat identitas atau informasi medis sensitif pasien.</span></label>
        <button class="btn-primary">Simpan versi draft</button>
    </form>
</x-layouts.app>
