<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Laporan presensi</title><style>body{font:14px Arial,sans-serif;color:#172033;margin:24px auto;padding:0 18px;max-width:1100px}table{border-collapse:collapse;width:100%;min-width:650px;margin:20px 0}td,th{border:1px solid #cbd5e1;padding:8px;text-align:left;overflow-wrap:anywhere}h1{font-size:24px}.scroll{overflow:auto}.notice{padding:14px;background:#f1f5f9}small{overflow-wrap:anywhere}@media print{.no-print{display:none}body{margin:0;font-size:10pt}.scroll{overflow:visible}table{min-width:0}thead{display:table-header-group}tr{break-inside:avoid}}</style></head><body>
<p class="no-print"><a href="{{ route('attendance.show', $p->ulid) }}">← Kembali ke presensi</a> · Gunakan menu cetak browser untuk mencetak atau menyimpan PDF.</p>
<h1>SIKORDIK — Laporan presensi</h1><p>{{ $snapshot['participant_name'] }} · {{ $snapshot['department_name'] }}</p><p>Periode {{ $snapshot['start_date'] }} – {{ $snapshot['end_date'] }} · Versi {{ $s->version }}</p>
<p class="notice"><strong>{{ ['draft' => 'DRAFT — BELUM DISAHKAN', 'sealed' => 'DISAHKAN KETUA KSM — TERKUNCI', 'superseded' => 'TIDAK BERLAKU — VERSI TELAH DIGANTIKAN'][$s->status] }}</strong><br>Ketua KSM: {{ $approver ?? '—' }} · Waktu pengesahan: {{ $s->approved_at ?? '—' }} WITA</p>
<p>Hari pendidikan: {{ count($snapshot['days']) }} · Belum diisi: {{ count($snapshot['missing']) }} · Belum terverifikasi: {{ $snapshot['pending'] }}</p>
<p>@foreach($snapshot['counts'] as $label => $count){{ ucfirst(str_replace('_', ' ', $label)) }}: {{ $count }}{{ !$loop->last ? ' · ' : '' }}@endforeach</p><p>Jumlah kehadiran hanya menghitung presensi terverifikasi.</p>
<div class="scroll"><table><thead><tr><th>Tanggal</th><th>Kehadiran</th><th>Lokasi / kegiatan</th><th>Verifikasi</th><th>Verifikator / waktu</th></tr></thead><tbody>@foreach($snapshot['rows'] as $r)<tr><td>{{ $r['date'] }}</td><td>{{ str_replace('_', ' ', $r['attendance_status']) }}</td><td>{{ $r['location_name'] }}<br>{{ $r['activity'] }}</td><td>{{ \App\Services\AttendanceService::LABELS[$r['status']] }}</td><td>{{ $r['verifier_name'] ?? '—' }}<br>{{ $r['verified_at'] ?? '—' }}</td></tr>@endforeach</tbody></table></div>
@if(count($snapshot['missing']))<p>Belum diisi: {{ implode(', ', $snapshot['missing']) }}</p>@endif
<small>Referensi laporan {{ $s->ulid }} · Dibuat {{ $s->created_at }} WITA. Status terkini harus diperiksa pada SIKORDIK. Laporan ini menggunakan snapshot versi tersimpan.</small>
</body></html>
