<x-layouts.app title="Presensi peserta">
    @php($user = auth()->user())
    @php($sealed = $service->sealed($p))
    <a class="text-sm text-brand-700" href="{{ route('attendance.index') }}">← Daftar presensi</a>
    <h1 class="mt-3 text-2xl font-bold">Presensi {{ $participant->name }}</h1>
    <p class="mt-2 text-sm text-slate-600">{{ json_decode($p->snapshot)->department }} · {{ $p->start_date }} – {{ $p->end_date }} · WITA</p>
    <p class="mt-2 text-sm text-slate-600">Hari pendidikan mengikuti jadwal terbit/selesai. Belum mengisi atau belum diverifikasi tidak otomatis dihitung tidak hadir.</p>
    <div class="my-6 grid gap-3 sm:grid-cols-3"><div class="card p-4">Hari pendidikan <strong class="block text-2xl">{{ count($days) }}</strong></div><div class="card p-4">Belum mengisi <strong class="block text-2xl">{{ count($snapshot['missing']) }}</strong></div><div class="card p-4">Belum terverifikasi <strong class="block text-2xl">{{ $snapshot['pending'] }}</strong></div></div>
    @if(count($snapshot['missing']))<p class="mb-4 break-words text-sm">Tanggal belum diisi: {{ implode(', ', $snapshot['missing']) }}</p>@endif
    @if($sealed)<div class="card mb-6 border-emerald-300 p-5 font-semibold text-emerald-800">Rekap disahkan dan dikunci. Koreksi admin membatalkan keabsahan versi ini dan memerlukan verifikasi serta pengesahan ulang.</div>@endif
    @if($access->owner($user, $p) && !$sealed)
        <details class="card mb-6 p-5"><summary class="cursor-pointer font-semibold">Isi presensi harian</summary><form class="mt-4 grid gap-4 md:grid-cols-2" method="POST" action="{{ route('attendance.save', $p->ulid) }}">@csrf @include('attendance.fields', ['row' => null])<div class="flex flex-wrap gap-3 md:col-span-2"><button class="btn-secondary" name="action" value="draft">Simpan draft</button><button class="btn-primary" name="action" value="submit">Ajukan ke pembimbing</button></div></form></details>
    @endif
    <h2 class="mb-3 text-lg font-bold">Presensi harian</h2>
    <div class="space-y-4">@forelse($rows as $row)<article class="card p-5">
        <div class="flex flex-wrap justify-between gap-2"><h3 class="font-bold">{{ $row->date }} · {{ ucfirst(str_replace('_', ' ', $row->attendance_status)) }}</h3><span class="badge-muted">{{ \App\Services\AttendanceService::LABELS[$row->status] }}</span></div>
        <p class="mt-3 whitespace-pre-wrap break-words text-sm">{{ $row->activity }}</p><p class="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{{ $row->notes }}</p>
        <p class="mt-2 text-xs text-slate-500">Versi {{ $row->revision }} · Diajukan {{ $row->submitted_at ?? '—' }} · Keputusan {{ $row->verified_at ?? '—' }} · Penugasan awal #{{ $row->original_assignment_id }}, verifikator saat ini #{{ $row->mentor_assignment_id }}</p>
        @if($row->decision_note)<p class="mt-2 text-sm">Catatan pembimbing: {{ $row->decision_note }}</p>@endif
        @if(($access->owner($user, $p) && !$sealed && !$row->admin_only && in_array($row->status, ['draft', 'rejected'])) || $access->admin($user))
            <details class="mt-4"><summary class="cursor-pointer font-semibold">{{ $access->admin($user) ? 'Koreksi administratif' : 'Perbaiki presensi' }}</summary><form class="mt-4 grid gap-4 md:grid-cols-2" method="POST" action="{{ route('attendance.save', $p->ulid) }}">@csrf @include('attendance.fields')
            @if($access->admin($user))<label class="md:col-span-2">Alasan koreksi<textarea class="input" name="reason" minlength="10" maxlength="2000" required></textarea></label><button class="btn-primary" name="action" value="correct">Koreksi dan minta verifikasi ulang</button>@else<div class="flex flex-wrap gap-3"><button class="btn-secondary" name="action" value="draft">Simpan draft</button><button class="btn-primary" name="action" value="submit">Ajukan kembali</button></div>@endif</form></details>
        @endif
        @if(!$sealed && in_array($row->status, ['waiting', 'corrected']) && $access->mentor($user, $row) && !$access->owner($user, $p))<form class="mt-4 space-y-3" method="POST" action="{{ route('attendance.decide', $row->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $row->revision }}"><label>Catatan keputusan<textarea class="input" name="reason" minlength="10" maxlength="2000" required></textarea></label><div class="flex gap-3"><button class="btn-primary" name="action" value="verify">Verifikasi</button><button class="btn-secondary" name="action" value="reject">Tolak</button></div></form>@endif
        @if(!$sealed && $access->admin($user) && in_array($row->status, ['waiting', 'corrected', 'rejected']))<details class="mt-4"><summary class="cursor-pointer">Ganti verifikator resmi</summary><form class="mt-3 space-y-3" method="POST" action="{{ route('attendance.replace', $row->ulid) }}">@csrf<input type="hidden" name="revision" value="{{ $row->revision }}"><label>Penugasan pengganti<select class="input" name="mentor_assignment_id" required>@foreach($assignments as $assignment)<option value="{{ $assignment->id }}">{{ $assignment->name }} · {{ $assignment->start_date }} – {{ $assignment->end_date }}</option>@endforeach</select></label><label>Alasan<textarea class="input" name="reason" minlength="10" maxlength="2000" required></textarea></label><button class="btn-secondary">Simpan pengganti</button></form></details>@endif
    </article>@empty<p class="card p-5 text-slate-500">Belum ada presensi.</p>@endforelse</div>
    <section class="card mt-6 p-5"><h2 class="text-lg font-bold">Rekap akhir & laporan</h2><p class="my-3 text-sm text-slate-600">Rekap tersedia setelah hari terakhir stase. Semua hari pendidikan wajib diisi dan diverifikasi sebelum disahkan Ketua KSM.</p>
    @if(!$sealed && $p->end_date < now()->toDateString() && ($access->manage($user, $p->department_id) || $access->chief($user, $p->department_id)))<form method="POST" action="{{ route('attendance.summary', $p->ulid) }}">@csrf<input type="hidden" name="version" value="{{ $summaries->first()->version ?? 0 }}"><button class="btn-secondary" name="action" value="generate">Buat rekap terbaru</button></form>@endif
    @foreach($summaries as $summary)<div class="mt-4 border-t pt-4"><p class="font-semibold">Versi {{ $summary->version }} · {{ ['draft' => 'Draft — belum disahkan', 'sealed' => 'Disahkan dan dikunci', 'superseded' => 'Tidak berlaku — digantikan'][$summary->status] }}</p><a class="mt-2 inline-block text-brand-700 underline" href="{{ route('attendance.report', $summary->ulid) }}">Buka laporan / cetak</a>@if($summary->status === 'draft' && $access->chief($user, $p->department_id) && !$access->owner($user, $p))<form class="mt-3" method="POST" action="{{ route('attendance.summary', $p->ulid) }}">@csrf<input type="hidden" name="version" value="{{ $summary->version }}"><button class="btn-primary" name="action" value="approve">Sahkan sebagai Ketua KSM & kunci</button></form>@endif</div>@endforeach</section>
    <details class="card mt-6 p-5"><summary class="cursor-pointer font-semibold">Riwayat perubahan</summary>@foreach($histories as $h)<div class="mt-3 border-t pt-3 text-sm"><p>{{ $h->created_at }} · {{ $h->event }} · pengguna #{{ $h->actor_id }}</p><p class="break-words">{{ $h->reason }}</p><details><summary class="cursor-pointer text-slate-500">Data sebelum dan sesudah</summary><pre class="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-all text-xs">{{ json_encode(['sebelum' => json_decode($h->before ?? 'null'), 'sesudah' => json_decode($h->after)], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></details></div>@endforeach<div class="mt-4">{{ $histories->links() }}</div></details>
</x-layouts.app>
