<x-layouts.app title="Checklist penyelesaian">
    <a class="text-brand-700 underline" href="{{ route('completion.index') }}">Kembali ke daftar</a>
    <h1 class="my-4 text-2xl font-bold">Checklist penyelesaian stase</h1>
    <p class="mb-4 text-sm">{{ json_decode($p->snapshot)->department }} · {{ $p->start_date }} – {{ $p->end_date }} · {{ str_replace('_', ' ', $p->status) }}{{ $p->archived_at ? ' · Arsip' : '' }}</p>
    @if($p->status === 'selesai')<p class="card mb-5 p-4">Penempatan dikunci. Data yang diizinkan tetap dapat dibaca dan diunduh melalui modul terkait. {{ $p->archived_at ? 'Arsip tidak menghapus data.' : '' }}</p>@endif
    <section class="card p-5"><h2 class="mb-3 text-lg font-semibold">Kelengkapan saat ini</h2><ul class="space-y-3">@foreach($checklist['checks'] as $c)<li class="flex items-start gap-3"><span class="shrink-0 rounded px-2 py-1 text-xs font-semibold {{ $c['ok'] ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900' }}">{{ $c['ok'] ? 'Lengkap' : 'Belum' }}</span><span>{{ $c['label'] }}</span></li>@endforeach</ul>
        <div class="mt-5 flex flex-wrap gap-3"><a class="text-brand-700 underline" href="{{ route('admissions.show', $p->ulid) }}">Dokumen</a><a class="text-brand-700 underline" href="{{ route('attendance.show', $p->ulid) }}">Presensi</a><a class="text-brand-700 underline" href="{{ route('logbooks.placement', $p->ulid) }}">Logbook</a><a class="text-brand-700 underline" href="{{ route('assessments.placement', $p->ulid) }}">Penilaian</a></div>
    </section>
    <section class="mt-5"><h2 class="mb-3 text-lg font-semibold">Kewajiban survei</h2><p class="mb-4 text-sm">Salin kode respons ke Google Form. Membuka tautan belum memenuhi kewajiban; Admin mencocokkan kode dengan respons yang masuk. Jangan masukkan nama pasien, NIK, nomor rekam medis, diagnosis, atau data medis sensitif.</p><div class="grid gap-4 lg:grid-cols-2">
        @foreach(\App\Services\SurveyService::KINDS as $kind => $label)
            @php $r = $surveys->get($kind); @endphp
            <article class="card min-w-0 p-5"><h3 class="font-semibold">{{ $label }}</h3><p class="my-3 text-sm">Status: {{ ['issued' => 'Token tersedia', 'submitted' => 'Menunggu verifikasi Admin', 'verified' => 'Terverifikasi', 'rejected' => 'Bukti belum cocok; periksa dan ajukan ulang'][$r->status ?? ''] ?? 'Belum dimulai' }}</p>
                @if($r && ($owner || $access->role(auth()->user(), ['admin-kordik', 'tim-kordik'])))<p class="break-all rounded bg-slate-100 p-3 font-mono text-sm">{{ $r->token }}</p><p class="my-3 text-sm">{{ $r->name }}</p><a class="text-brand-700 underline" href="{{ $r->url }}" target="_blank" rel="noopener noreferrer">Buka Google Form ↗</a>@endif
                @if(in_array($p->status, ['sedang_stase', 'menunggu_penyelesaian']) && ! $p->archived_at)
                    @if($owner && (! $r || in_array($r->status, ['issued', 'rejected'])))<form class="mt-4 space-y-3" method="POST" action="{{ route('completion.survey', $p->ulid) }}">@csrf<input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="revision" value="{{ $r->revision ?? 0 }}"><input type="hidden" name="action" value="{{ $r ? 'submit' : 'start' }}"><label class="flex items-start gap-2"><input type="checkbox" name="confirm" value="1" required><span>{{ $r ? 'Saya telah mengirim respons dengan kode ini, tanpa identitas/data medis pasien.' : 'Saya memahami ketentuan privasi dan akan memakai kode respons yang diterbitkan.' }}</span></label><button class="btn-primary">{{ $r ? 'Ajukan verifikasi respons' : 'Terbitkan kode respons' }}</button></form>@endif
                    @if(! $owner && $access->role(auth()->user(), ['admin-kordik']) && $r?->status === 'submitted')<form class="mt-4 space-y-3" method="POST" action="{{ route('completion.survey', $p->ulid) }}">@csrf<input type="hidden" name="kind" value="{{ $kind }}"><input type="hidden" name="revision" value="{{ $r->revision }}"><label class="block">Hasil pemeriksaan<select name="action"><option value="verify">Respons dengan kode ini ditemukan dan lengkap</option><option value="reject">Belum ditemukan / belum lengkap</option></select></label><label class="flex items-start gap-2"><input type="checkbox" name="confirm" value="1" required><span>Saya telah memeriksa respons Google Form dan mencocokkan kode ini.</span></label><button class="btn-secondary">Simpan pemeriksaan</button></form>@endif
                @endif
            </article>
        @endforeach
    </div></section>
    @php
        $actions = [];
        if (! $owner && ! $p->archived_at) {
            if ($access->role(auth()->user(), ['admin-kordik'])) {
                if (!$pending && in_array($p->status, ['sedang_stase', 'menunggu_penyelesaian']) && $checklist['ready']) $actions['submit'] = 'Ajukan penyelesaian';
                if (!$pending && $p->status === 'selesai') { $actions['reopen_request'] = 'Ajukan pembukaan kembali'; if ($p->completed_at && \Carbon\Carbon::parse(max($p->completed_at, $p->actual_end_date ?? $p->end_date))->addYears(3)->lte(now())) $actions['archive'] = 'Arsipkan setelah retensi tiga tahun'; }
                if ($pending) $actions['withdraw'] = 'Tarik permohonan untuk pemeriksaan ulang';
                if ($pending?->kind === 'reopen' && $pending->status === 'approved' && $pending->decided_by != auth()->id()) $actions['reopen_execute'] = 'Laksanakan pembukaan kembali';
            }
            if ($access->role(auth()->user(), ['tim-kordik']) && $pending?->status === 'pending' && $pending->requested_by != auth()->id()) { $actions['approve'] = 'Setujui permohonan'; $actions['reject'] = 'Tolak permohonan'; }
        }
    @endphp
    @if($actions)<form class="card mt-5 space-y-4 p-5" method="POST" action="{{ route('completion.transition', $p->ulid) }}">@csrf<h2 class="text-lg font-semibold">Pemeriksaan dan keputusan</h2><input type="hidden" name="revision" value="{{ $p->revision }}">@if($pending)<input type="hidden" name="request_id" value="{{ $pending->id }}"><input type="hidden" name="request_revision" value="{{ $pending->revision }}"><p>Permohonan: {{ $pending->kind === 'completion' ? 'Penyelesaian' : 'Pembukaan kembali' }} · {{ $pending->status }}</p>@endif<label class="block">Tindakan<select name="action">@foreach($actions as $value => $label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label><label class="block">Alasan dan hasil pemeriksaan<textarea name="reason" minlength="10" maxlength="2000" required>{{ old('reason') }}</textarea></label><label class="flex items-start gap-2"><input type="checkbox" name="confirm" value="1" required><span>Saya telah memeriksa kewajiban dan menyatakan tindakan ini sesuai kewenangan saya. Alasan tidak memuat data pasien.</span></label><button class="btn-primary">Simpan tindakan</button></form>@endif
    <section class="card mt-5 space-y-4 p-5"><h2 class="text-lg font-semibold">Riwayat permohonan dan pengesahan</h2>@forelse($requests as $r)<article class="min-w-0 border-t pt-3"><p class="font-semibold">{{ $r->kind === 'completion' ? 'Penyelesaian' : 'Pembukaan kembali' }} · {{ $r->status }}</p><p class="mt-2 text-sm">{{ $r->created_at }} · {{ $r->reason }}</p>@if($r->decision_reason)<p class="mt-2 text-sm">Keputusan: {{ $r->decision_reason }}</p>@endif @if($r->approval)@php($seal = json_decode($r->approval))<p class="mt-2 break-all text-sm">{{ $seal->number }} · {{ $seal->name }} · {{ $seal->job_title }} · {{ $seal->at }}</p><p class="mt-2 break-all font-mono text-xs">SHA-256: {{ $seal->sha256 }}</p>@endif</article>@empty<p class="text-sm">Belum ada permohonan.</p>@endforelse
        @foreach($history as $h)<p class="border-t pt-3 text-sm">{{ $h->created_at }} · {{ str_replace('_', ' ', $h->action) }} · {{ $h->reason }}</p>@endforeach
    </section>
</x-layouts.app>
